### ISSUE TITLE
Программа ничего не делает?

### ISSUE THREAD

**Issue by evilunyuu** [AnastasiHa/lab22#2]
По условию задачи, программа должна была вывести абзацы текста в обратном порядке. Но выводит почему-то в обычном порядке.

**Comment by chessks** [comment]
всмысле??? Задача на сложение двух числе. огромных. которые представленые через строки и выполнено сложение, а затем выдан ответ

**Comment by evilunyuu** [comment]
Цитирую задание 22:
Задача 22
Написать программу, выводящую на консоль содержимое текстового
файла с обратным порядком абзацев. Разделителем между абзацами
считать пустую строку.

**Comment by chessks** [comment]
у меня задача 9

**Comment by chessks** [comment]
я Кудинов Александр

**Comment by chessks** [comment]
Кудинов А.П.Вчера, в 17:22
Кудинов Александр Петрович 9 задача

Харитонова Анастасия 22я задача

**Comment by evilunyuu** [comment]
Ну так а чья эта репа?

**Comment by AnastasiHa** [comment]
Программа моя и работает нормально (Анастасия Харитонова)
[text.txt](https://github.com/AnastasiHa/lab22/files/4657831/text.txt)
![ob7VhD85yMk](https://user-images.githubusercontent.com/65583924/82466376-c57b6300-9ad9-11ea-9ed5-092910150f2c.jpg)

**Comment by evilunyuu** [comment]
![Снимок экрана_2020-05-20_20-44-54](https://user-images.githubusercontent.com/12897761/82467246-e7c1b080-9ada-11ea-87bb-4748c09c8148.png)
А код в репозитории точно актуальный? Потому что у меня программа выдаёт вот это...

**Comment by AnastasiHa** [comment]
#include <iostream>
#include <string>
#include <fstream>
#include <Windows.h>
#include <vector>

int main(void) {
    SetConsoleCP(1251);
    SetConsoleOutputCP(1251);
    std::string input, ask;
    std::string all, getcontent;
    int i=0, p=0, j=0;
    std::vector<std::string> arr{};
    std::ifstream infile;
    infile.open("text.txt");
    if(infile.is_open()) {
        while(getline(infile,getcontent)) {
            arr.push_back(getcontent);
            i++;
        }
    }
    p=i;
    std::cout << "Âàðèàíò 22 ïðåîáðàçîâàíèå àáçàöåâ" << std::endl;
    std::cout << "Àâòîð: Õàðèòîíîâà Àíàñòàñèÿ" << std::endl << std::endl;
    std::cout << "Èçìåíåííûé òåêñò:" << std::endl;
блок перебирающий строки файла с конца. и если видит пустую строку то выводит строки от этой строки до p на печать
    for(i=p-1;i>=0;i--) {
        if(arr[i] == "") {
            for(j=i+1;j<p;j++) {
                std::cout << arr[j] << std::endl;
            }
            std::cout << std::endl;
Устанавливается начало прошлого абзаца что чтобы перебирало строки до него
            p=i;
        }
    }
Самый первый абзац(выводится последним) вынесен отдельно блоком кода потому что перед ним пустой строки нет
    for(j=0;j<p;j++) {
        std::cout << arr[j] << std::endl;
    }
    getline(std::cin, input);

    return 0;
}

**Comment by evilunyuu** [comment]
Код лучше в репозиторий поместить, а не сюда. Отсюда его невозможно правильно вытащить из-за форматирования.

**Comment by AnastasiHa** [comment]
этот файл и взят из репозитория 
https://github.com/AnastasiHa/lab22/blob/master/main.cpp

**Comment by evilunyuu** [comment]
Всё, понятно, в чём была проблема. Очередные виндовсопроблемы. У винды перевод строки не как у людей...
Принято.
